apiVersion: v1
kind: Service
metadata:
  name: {{ template "dask.fullname" . }}-worker
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: worker
spec:
  ports:
    - name: {{ template "dask.fullname" . }}-jupyter
      port: {{ .Values.worker.servicePort }}
      targetPort: 8001
  selector:
    app: {{ template "dask.name" . }}
    release: {{ .Release.Name | quote }}
    component: worker
  type: {{ .Values.worker.serviceType }}
